spring:
  datasource:
    url: jdbc:mysql://localhost:3306/powernode
    username: root
    password: 123456789
    diver-class-name: com.mysql.cj.jdbc.Driver



mybatis:
  mapper-locations: classpath:/mapper/*.xml # mapper映射文件路径
server:
  port: 8083